# Generated by Django 2.2 on 2022-05-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_list_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='group_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
