# Generated by Django 2.2 on 2022-05-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_auto_20220514_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='renew_date',
            field=models.DateField(blank=True, default='None', null=True),
        ),
    ]
