# Generated by Django 2.2 on 2022-05-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20220517_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='renew_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
