# Generated by Django 2.2 on 2022-05-18 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_auto_20220517_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='test_app.Location'),
        ),
    ]
