# Generated by Django 2.2 on 2022-05-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_auto_20220517_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.List'),
        ),
    ]
